/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.hamcrest.CoreMatchers.equalTo;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.setup.MockMvcBuilders.webAppContextSetup;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.web.context.WebApplicationContext;

import br.com.scopus.arquitetura.devops.HelloWorldApplication;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = HelloWorldApplication.class)
@WebAppConfiguration
public class HelloWorldTest {
	
	private MockMvc mockMvc;
	
	@Autowired
	private WebApplicationContext webApplicationContext;
	
	@Before
	public void setup() throws Exception {
		this.mockMvc = webAppContextSetup(webApplicationContext).build();
	}

    @Test 
    public void helloWorld() throws Exception {
    	mockMvc.perform(MockMvcRequestBuilders.get("/api/v1/"))
    	.andExpect(MockMvcResultMatchers.status().isOk())
    	.andExpect(content().string(equalTo("{\"id\":1,\"conteudo\":\"Hello World!\"}")));
    }
}
